---
version: 2.1
commands:
  install-tool:
    parameters:
      tool:
        type: string
    steps:
      - restore_cache:
          key: << parameters.tool >>-{{ .Environment.CIRCLE_SHA1 }}

workflows:
  build:
    jobs:
      - save-conftest
      - save-golangci-lint
      - save-shfmt
      - main:
          requires:
            - save-conftest
            - save-golangci-lint
            - save-shfmt

jobs:
  main:
    docker:
      - image: alpine:3.12.0
    steps:
      - install-tool:
          tool: conftest
      - install-tool:
          tool: golangci-lint
      - install-tool:
          tool: shfmt
      - run:
          name: check conftest
          command: |
            which conftest
            conftest --version
      - run:
          name: check golangci-lint
          command: |
            which golangci-lint
            golangci-lint --version
      - run:
          name: check shfmt
          command: |
            which shfmt
            shfmt --version

  save-conftest:
    docker:
      - image: instrumenta/conftest:v0.19.0
    steps:
      - save_cache:
          key: conftest-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/local/bin/conftest
            - /conftest

  save-golangci-lint:
    docker:
      - image: golangci/golangci-lint:v1.28.3-alpine
    steps:
      - save_cache:
          key: golangci-lint-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/bin/golangci-lint

  save-shfmt:
    docker:
      - image: mvdan/shfmt:v3.1.0-alpine
    steps:
      - save_cache:
          key: shfmt-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /bin/shfmt
