---
version: 2.1
commands:
  install-conftest:
    steps:
      - restore_cache:
          key: conftest-{{ .Environment.CIRCLE_SHA1 }}
  install-golangci-lint:
    steps:
      - restore_cache:
          key: golangci-lint-{{ .Environment.CIRCLE_SHA1 }}

workflows:
  build:
    jobs:
      - save-conftest
      - save-golangci-lint
      - main:
          requires:
            - save-conftest
            - save-golangci-lint

jobs:
  main:
    docker:
      - image: alpine:3.12.0
    steps:
      - install-conftest
      - install-golangci-lint
      - run:
          name: check conftest
          command: |
            which conftest
            conftest --version
      - run:
          name: check golangci-lint
          command: |
            which golangci-lint
            golangci-lint --version

  save-conftest:
    docker:
      - image: instrumenta/conftest:v0.19.0
    steps:
      - save_cache:
          key: conftest-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/local/bin/conftest
            - /conftest

  save-golangci-lint:
    docker:
      - image: golangci/golangci-lint:v1.28.3-alpine
    steps:
      - save_cache:
          key: golangci-lint-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/bin/golangci-lint
