---
version: 2.1
commands:
  install-tool:
    parameters:
      tool:
        type: string
    steps:
      - restore_cache:
          key: << parameters.tool >>-{{ .Environment.CIRCLE_SHA1 }}
  check-tool:
    parameters:
      tool:
        type: string
    steps:
      - run:
          name: check << parameters.tool >>
          command: |
            command -v << parameters.tool >>
            << parameters.tool >> --version

workflows:
  build:
    jobs:
      - save-conftest
      - save-golangci-lint
      - save-shfmt
      - save-shellcheck
      - main:
          requires:
            - save-conftest
            - save-golangci-lint
            - save-shfmt
            - save-shellcheck

jobs:
  main:
    docker:
      - image: alpine:3.12.0
    steps:
      - install-tool:
          tool: conftest
      - install-tool:
          tool: golangci-lint
      - install-tool:
          tool: shfmt
      - install-tool:
          tool: shellcheck
      - check-tool:
          tool: conftest
      - check-tool:
          tool: golangci-lint
      - check-tool:
          tool: shfmt
      - check-tool:
          tool: shellcheck

  save-conftest:
    docker:
      - image: instrumenta/conftest:v0.19.0
    steps:
      - save_cache:
          key: conftest-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/local/bin/conftest
            - /conftest

  save-golangci-lint:
    docker:
      - image: golangci/golangci-lint:v1.29.0-alpine
    steps:
      - save_cache:
          key: golangci-lint-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /usr/bin/golangci-lint

  save-shfmt:
    docker:
      - image: mvdan/shfmt:v3.1.2-alpine
    steps:
      - save_cache:
          key: shfmt-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /bin/shfmt

  save-shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:v0.6.0
    steps:
      - save_cache:
          key: shellcheck-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /bin/shellcheck
